APP_NAME = "盘盘圈——飞盘地图"
ALL = "全部"

TAB1_NAME = "飞盘地图"
TAB2_NAME = "关于我们"
TAB3_NAME = ""

INITIAL_PROVINCE = ALL
INITIAL_CITY = ALL

MAP_POPUP_PROVINCE="所在省份 : "
MAP_POPUP_CITY="所在城市 : "
MAP_POPUP_NAME="队伍名称 : "
MAP_POPUP_TYPE="队伍类别 : "
MAP_POPUP_CONTACT="联系方式 : "
MAP_POPUP_OTHERS="其他信息 : "
MAP_POPUP_TIME="成立时间 : "
MAP_POPUP_ADDRESS="队伍地址 : "
MAP_POPUP_COMPETIVE="竞技队伍 : "
MAP_POPUP_COACH="队伍教练 : "
MAP_POPUP_SCALE="队伍规模 : "
MAP_POPUP_FEE="队伍费用 : "

SCHOOL_FRISBEE_DATA_PATH="./data/frisbee.csv"

LABEL_CITY="城市"
LABEL_PROVINCE="省份"
LABEL_TYPE="类别"